README.md

test checkin

---

controllers/backup_test.go
controllers/suite_test.go

Adding unit tests for backup utility functions

---

CONTRIBUTING.md
sonar-project.properties

Signed-off-by: Joshua Packer <jpacker@redhat.com>
* Reference that pull request (commits) must be signed.
* Trigger the first PROW build

Add signed reference to contribution md

---

config/rbac/role.yaml
controllers/backup_controller.go

Another fix for this, with the latest code
https://github.com/open-cluster-management/backlog/issues/15746
Add list, watch for the deletebackuprequests

update roles for deletebackuprequests

---

api/v1beta1/schedule_types.go
config/crd/bases/cluster.open-cluster-management.io_backupschedules.yaml
controllers/schedule.go
controllers/schedule_controller.go
go.mod
go.sum

https://github.com/open-cluster-management/backlog/issues/15808
https://github.com/open-cluster-management/backlog/issues/15810
TODO:

Validate cron job schedule and set phase and message

---

README.md
config/rbac/role.yaml
controllers/restore_controller.go

errata to previous commit

---

controllers/schedule_controller.go

for defect https://github.com/open-cluster-management/backlog/issues/16065

don't create backup schedule if storage location is not available

---

api/v1beta1/restore_types.go
config/crd/bases/cluster.open-cluster-management.io_restores.yaml
config/rbac/role.yaml
controllers/restore.go
controllers/restore_controller.go
controllers/schedule_controller_test.go
controllers/suite_test.go
go.mod
go.sum
main.go

Still some work to do: to fix clusterroles and clusterrolebindings. Few TODOs

Restore controller fixes.

---

controllers/schedule_controller.go

- Fixing an RBAC issue missed in this PR https://github.com/open-cluster-management/cluster-backup-operator/pull/42
- Fixing some Sonar issues
NOTE: The missing RBAC rule already exists in the role.yaml file https://github.com/open-cluster-management/cluster-backup-operator/blob/6acef034aca43ebe93eb58f8b5f51e0a7aa8d05e/config/rbac/role.yaml#L156

Fixing an rbac and some sonar issues

---

config/crd/bases/velero.io_backupstoragelocations.yaml
config/crd/bases/velero.io_deletebackuprequests.yaml
config/crd/bases/velero.io_restores.yaml
config/crd/bases/velero.io_schedules.yaml
config/crd/kustomization.yaml
config/rbac/role.yaml
controllers/schedule_controller.go

Fixing https://github.com/open-cluster-management/backlog/issues/16127

Add Velero crds to be installed by this operator

---

api/v1beta1/restore_types.go
config/crd/bases/cluster.open-cluster-management.io_restores.yaml
config/samples/cluster_v1beta1_restore.yaml
controllers/restore_controller.go
controllers/restore_controller_test.go

https://github.com/open-cluster-management/backlog/issues/16185

Update restore API, Add tests

---

README.md

https://github.com/open-cluster-management/backlog/issues/16303
fyi .. @thuyn-581

update readme for restore and backup details

---

api/v1beta1/restore_types.go
controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/schedule_controller_test.go

- https://github.com/open-cluster-management/backlog/issues/16304
- https://github.com/open-cluster-management/backlog/issues/15944
- Fix a bug in unit tests , resulted in more coverage

check velero status before restore, fix sonar, fix tests

---

controllers/schedule_test.go

To improve coverage for schedule utility functions.

to add schedule tests

---

config/rbac/role.yaml
controllers/schedule_controller.go

https://github.com/open-cluster-management/backlog/issues/16452

add cluster pools role

---

README.md

update readme for restore file types

---

README.md

Update readme or oadp olm installation to point to the doc page describing how to setup the storage connection

update oadp install link

---

controllers/backup_test.go
controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/schedule_controller_test.go
controllers/utils.go

https://github.com/open-cluster-management/backlog/issues/16630

create valid k8s name and add tests

---

README.md

Update restore sample in the readme

---

controllers/schedule_controller_test.go

https://github.com/open-cluster-management/backlog/issues/16630

test coverage for storage location not found

---

controllers/restore_controller_test.go

https://github.com/open-cluster-management/backlog/issues/16630

test restore with no storage location object

---

controllers/schedule_controller_test.go

https://github.com/open-cluster-management/backlog/issues/16630

test update schedule ttl, should call delete velero schedules and recreation

---

Dockerfile
go.mod

https://github.com/open-cluster-management/backlog/issues/15570

Upgrade to go 1.17

---

go.mod

https://github.com/open-cluster-management/backlog/issues/18020

Update go lang to 1.17 - run go mod tiny

---

README.md

no-op change to verify-ff to release 2.5

---

controllers/schedule_controller.go
controllers/schedule_controller_test.go

https://github.com/open-cluster-management/backlog/issues/18068

Recreate manually deleted velero schedules

---

controllers/restore_controller.go
controllers/schedule_controller.go

https://github.com/open-cluster-management/backlog/issues/18187

fix oadp changes in version 0.5

---

main.go

https://github.com/open-cluster-management/backlog/issues/18424

Enable leader election for controller manager

---

controllers/backup.go

https://github.com/securego/gosec#annotating-code

fix gosec G101 false positive

---

controllers/backup.go

https://github.com/open-cluster-management/cluster-backup-operator/pull/94
https://github.com/open-cluster-management/backlog/issues/18200

include core.observatorium.io in dynamic CRD for backup

---

controllers/backup.go
controllers/backup_test.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go
controllers/suite_test.go
controllers/utils.go

Changes : 
- exclude from the generic backup resources covered by the managed cluster backup or resources backup
- validate generic resources and resources backup included/excluded resources content
- fix code smells

add dynamic discovery tests

---

controllers/backup.go
controllers/restore.go
controllers/restore_controller.go
controllers/schedule.go

fix code smells

---

controllers/backup.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go

https://github.com/open-cluster-management/backlog/issues/18469

delete backups in groups using timestamp

---

controllers/backup.go

https://github.com/open-cluster-management/backlog/issues/18469

fix vulnerability

---

controllers/restore_controller_test.go

Adding unit tests : Bugzilla – Bug 2034279 - Restore/backup shows up as Validation failed but the restore backup status in ACM shows success

Add unit tests

---

controllers/backup.go

https://github.com/stolostron/backlog/issues/18514#issuecomment-1006051587
Backup search resources

include search api group

---

controllers/backup.go

https://github.com/stolostron/backlog/issues/18821
Changes : 
- use backups creationTime to find related backups; related backups should be in the 2s time interval on creation
- they also should have the prefix as defined by the acm backups list

fix delete old backups

---

api/v1beta1/restore_types.go
controllers/restore_controller.go
controllers/restore_controller_test.go

https://github.com/stolostron/backlog/issues/18998

Map Velero's partially failed phase to finished with errors phase

---

api/v1beta1/restore_types.go
controllers/restore_controller.go

Fixes for:
https://github.com/stolostron/backlog/issues/18630
https://github.com/stolostron/backlog/issues/18998

Fix restore status

---

controllers/backup.go
controllers/suite_test.go

observability #18509(https://github.com/stolostron/backlog/issues/18509)
cluster [#18513](https://github.com/stolostron/backlog/issues/18513)

remove obs addon and clusterclaims

---

controllers/restore_test.go
controllers/schedule_controller_test.go
controllers/utils_test.go

more tests

---

controllers/backup.go
controllers/schedule_controller.go

https://github.com/stolostron/backlog/issues/19409

add schedule label annotation

---

README.md
api/v1beta1/schedule_types.go
config/crd/bases/cluster.open-cluster-management.io_backupschedules.yaml
config/samples/cluster_v1beta1_backupschedule.yaml
controllers/backup.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go

https://github.com/stolostron/backlog/issues/19444

remove maxBackups spec prop

---

controllers/restore.go
controllers/restore_controller.go
controllers/restore_controller_test.go

https://github.com/stolostron/backlog/issues/19535

Skip setting error status if restore is completed

---

controllers/restore.go
controllers/restore_controller.go
controllers/restore_test.go
controllers/schedule_controller.go

https://github.com/stolostron/backlog/issues/19535
- Fix restore status
- Fix lint errors

Fix for setting status when no velero restores found

---

config/crd/bases/velero.io_backups.yaml
config/crd/bases/velero.io_backupstoragelocations.yaml
config/crd/bases/velero.io_restores.yaml
config/crd/bases/velero.io_schedules.yaml
controllers/restore_controller_test.go

https://github.com/stolostron/backlog/issues/19696

Update Velero CRDs

---

controllers/restore.go
controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/suite_test.go

add some tests for cleanup

---

controllers/restore_controller.go
controllers/restore_controller_test.go

https://github.com/stolostron/backlog/issues/19537

Ignore restore if other restores are running

---

controllers/restore_controller_test.go
controllers/suite_test.go
controllers/utils_test.go

more tests for cleanup

---

controllers/restore.go
controllers/restore_controller.go

Changes : 
- call clean up for all restores and after that call the restore
- call patch after delete when deleted resource uses finalizers

delete resources after patch

---

controllers/restore_controller.go

Some fixes in setting restore status

---

README.md

No op change to trigger sonar on main branch

---

controllers/schedule.go
controllers/schedule_controller.go

https://github.com/stolostron/backlog/issues/19469

stop reconciling backupschedule if phase is Collision

---

controllers/backup.go
controllers/restore.go
controllers/restore_controller.go

https://github.com/stolostron/backlog/issues/19144

create backup schedule after cluster activation

---

controllers/restore_controller.go
controllers/schedule_controller.go

fix vulnerabilites

---

api/v1beta1/restore_types.go
config/crd/bases/cluster.open-cluster-management.io_restores.yaml
config/samples/cluster_v1beta1_restore.yaml
config/samples/cluster_v1beta1_restore_passive.yaml
config/samples/cluster_v1beta1_restore_passive_activate.yaml
controllers/restore.go
controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/restore_test.go

https://github.com/stolostron/backlog/issues/19928

clean up all resources

---

config/samples/cluster_v1beta1_backupschedule.yaml
config/samples/cluster_v1beta1_restore.yaml
config/samples/cluster_v1beta1_restore_passive.yaml
config/samples/cluster_v1beta1_restore_passive_activate.yaml
controllers/restore.go

make the cleanupOption to default deleting only resources created by restore

fix delete on restore

---

README.md

https://github.com/stolostron/backlog/issues/19904

update readme with 2.5 content

---

api/v1beta1/restore_types.go
config/crd/bases/cluster.open-cluster-management.io_restores.yaml
config/samples/cluster_v1beta1_restore_passive.yaml
controllers/restore.go
controllers/restore_controller.go

https://github.com/stolostron/backlog/issues/19470

Sync restore

---

config/crd/bases/cluster.open-cluster-management.io_restores.yaml

Missed checkin of CRD info https://github.com/stolostron/cluster-backup-operator/pull/160

update crd description

---

README.md

https://github.com/stolostron/backlog/issues/19928

add cleanup details to readme

---

README.md

update what we backup info

---

config/samples/cluster_v1beta1_restore_passive.yaml
controllers/restore.go
controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/schedule_controller.go

Don't count errors when finding latest backups

---

README.md

https://github.com/stolostron/backlog/issues/20486

some readme updates on cluster-activation label

---

controllers/utils.go

https://github.com/stolostron/backlog/issues/20541

get clusterID from clusterVersion

---

README.md

https://github.com/stolostron/backlog/issues/19904

update readme on restore

---

controllers/schedule_controller.go

https://github.com/stolostron/backlog/issues/20557

Update backup status to collision before deleting Velero schedules

---

README.md

https://github.com/stolostron/backlog/issues/20629

document PartiallyFailed resources

---

README.md
config/samples/cluster_v1beta1_restore_passive_sync.yaml

https://github.com/stolostron/backlog/issues/19470
https://github.com/stolostron/backlog/issues/20902

document restore sync option

---

controllers/restore_controller.go

https://github.com/stolostron/backlog/issues/20985

update status when prepare to restore

---

README.md

https://github.com/stolostron/backlog/issues/20991
Changes : 
- document that activation data is also stored by the acm-managed-clusters backup
I'll use https://github.com/stolostron/backlog/issues/20830 to clarify if the list under the acm-managed-clusters backup is complete and correct ( re cclaim and cpool being backed up at activation time )

document activation data not using the backup cluster-activation label

---

controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go
main.go

https://github.com/stolostron/backlog/issues/21017

add backup labels for pool secrets

---

controllers/schedule.go

https://github.com/stolostron/backlog/issues/20830
ClusterDeployments created from cluster claims cannot be restored on a new hub because the clusterdeploymentvalidators webhook to disallow creating a ClusterDeployment with the ClusterClaim already set. 
The fix is to add a label to the ClusterDeployments backed up and having the ClusterClaim set 
https://github.com/openshift/hive/pull/1729
The webhook will ignore these resources 
{"errors":{"namespaces":{"vb-pool-gf5gq":["error restoring clusterdeployments.hive.openshift.io/vb-pool-gf5gq/vb-pool-gf5gq: admission webhook \"clusterdeploymentvalidators.admission.hive.openshift.io\" denied the request: ClusterDeployment.hive.openshift.io \"vb-pool-gf5gq\" is invalid: …

add hive.openshift.io/disable-creation-webhook-for-dr to cd from claims

---

controllers/backup.go

https://github.com/stolostron/backlog/issues/21097

Fix the ttl for validation backups

---

config/rbac/role.yaml
controllers/restore_controller.go
controllers/schedule_controller.go

Add rbac for deletebackuprequests to controllers

---

config/crd/bases/velero.io_deletebackuprequests.yaml
config/crd/kustomization.yaml
controllers/backup.go
controllers/schedule_controller_test.go

add tests for delete backup

---

controllers/restore_controller_test.go

tests for restore isNewBackupAvailable

---

README.md

No Op change

---

controllers/restore_controller_test.go

Remove the test with intermittent failures

---

controllers/backup.go
controllers/restore_test.go
controllers/schedule_controller.go

test coverage

---

README.md

rename Hub D to Hub N

---

controllers/restore_test.go

tests for dynamic delete

---

controllers/restore_controller.go
controllers/restore_controller_test.go

When restoring get the latest backup in completed or partiallyfailed status

use backup if partiallyfailed

---

controllers/backup.go
controllers/schedule.go

https://github.com/stolostron/backlog/issues/21499

label ai secrets and backup metal3 group

---

README.md

Update readme with information about data protection

---

README.md

Update table of contents with DocToccing

---

config/samples/cluster_v1beta1_restore.yaml
config/samples/cluster_v1beta1_restore_passive.yaml
config/samples/cluster_v1beta1_restore_passive_activate.yaml
config/samples/cluster_v1beta1_restore_passive_sync.yaml

update cleanupBeforeRestore info to required

---

README.md

Add DataProtectionApplication policy template to the readme

---

README.md

Fix cluster activation label in readme

---

README.md

https://github.com/stolostron/backlog/issues/22075
https://github.com/stolostron/backlog/issues/22160

No Op change for a new build to pick latest images

---

controllers/backup.go

https://github.com/stolostron/backlog/issues/22343

backup api groups with suffix .hive.openshift.io

---

README.md

related to https://github.com/stolostron/backlog/issues/22236

README changes: document local-cluster changes are not restored

---

README.md

https://github.com/stolostron/backlog/issues/22501

Fix backup label instructions and add examples

---

README.md

Signed-off-by: Omar Farag <ofarag@redhat.com>
https://github.com/stolostron/backlog/issues/23687

Changed command in 'Scheduling a cluster backup' section

---

controllers/pre_backup.go

https://github.com/stolostron/backlog/issues/23864

annotate secret with expirationTimestamp

---

controllers/pre_backup.go
controllers/utils.go

https://github.com/stolostron/backlog/issues/24004

ignore hive clusters when creating MSA

---

controllers/pre_backup.go

use klusterlet for MSA role binding

---

controllers/pre_backup.go
controllers/pre_backup_test.go
controllers/schedule_controller_test.go

Update MSA validity token if the BackupSchedule tokenTTL has changed

patch MSA token validity when updated

---

README.md
config/samples/cluster_v1beta1_backupschedule_msa.yaml

readme for the MSA feature

---

Dockerfile
go.mod
go.sum

https://github.com/stolostron/backlog/issues/22428

Use golang 1.18 for 2.4 release

---

controllers/restore.go

remove unused const

---

README.md

Recommend to use server side encryption

update encryption info

---

controllers/restore.go
controllers/restore_controller.go
controllers/utils.go
controllers/utils_test.go

add tests for managedClusterShouldReimport

add tests for postRestoreActivation

---

controllers/utils_test.go

cover all lines for managedClusterShouldReimport

add tests for managedClusterShouldReimport

---

controllers/pre_backup.go
controllers/pre_backup_test.go
controllers/utils_test.go

getBackupTimestamp and createMSA tests

---

controllers/restore.go

Fix condition orders in postRestoreActivation

---

README.md
controllers/pre_backup.go
controllers/restore_test.go

https://github.com/stolostron/backlog/issues/25236

document hive deployment secrets backup

---

controllers/pre_backup_test.go
controllers/restore.go
controllers/restore_controller.go
controllers/restore_test.go
controllers/suite_test.go

add tests for getVeleroBackupName

---

controllers/restore.go
controllers/restore_controller.go
controllers/restore_test.go

tests for isOtherResourcesRunning

---

controllers/restore_controller.go
controllers/restore_controller_test.go

test coverage for restoring only managed clusters

---

controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_test.go

tests for deleteVeleroSchedules and isRestoreRunning

---

controllers/restore_test.go

tests for deleteDynamicResource

---

controllers/pre_backup_test.go
controllers/restore.go
controllers/schedule_controller_test.go
controllers/suite_test.go

https://github.com/stolostron/backlog/issues/25492
Also added more tests for dynamic client

fix label annotation when CleanupTypeAll

---

main.go

https://github.com/stolostron/backlog/issues/25372

Set human readable time format for logger

---

controllers/backup_test.go
controllers/create_helper.go
controllers/pre_backup_test.go
controllers/restore_controller_test.go
controllers/restore_test.go
controllers/schedule_controller_test.go
controllers/schedule_test.go
controllers/utils_test.go

move resources creation under createHelper

refactor tests

---

controllers/restore.go
controllers/restore_test.go

https://github.com/stolostron/backlog/issues/25595

add tests for isOtherResourcesRunning

---

controllers/restore_controller.go

https://github.com/stolostron/backlog/issues/26035

Fix for when the same backupName is retrieved for all credential types

---

controllers/backup.go
controllers/create_helper.go
controllers/pre_backup.go
controllers/restore_controller.go
controllers/restore_post.go
controllers/restore_post_test.go

Changes:
- remove delta for resources and generic resources
- delta for managed clusters has been commented out, it will be done in a separate PR

delete delta for restored resources and managed clusters

---

README.md

Simplify the doc on how to enable the MSA feature

update doc on auto import feature

---

README.md

Update readme
MSA component is now owned by MCE

MSA component is now owned by MCE

---

controllers/pre_backup.go
controllers/pre_backup_test.go
controllers/schedule_controller.go

removed reference to MCH from the MSA not installed error

update MSA not installed error

---

controllers/schedule_controller.go

https://github.com/stolostron/backlog/issues/24206

log MSA CRD error

---

controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_test.go

https://github.com/stolostron/backlog/issues/24206

refactor MSA validation

---

api/v1beta1/restore_types.go
config/crd/bases/cluster.open-cluster-management.io_restores.yaml
controllers/restore_controller_test.go
controllers/restore_post.go
controllers/restore_test.go

https://github.com/stolostron/backlog/issues/26192
Remove CleanupTypeAll option

remove references to CleanupTypeAll

---

controllers/restore.go

https://github.com/stolostron/backlog/issues/24032#issuecomment-1277269804

Update activation label on auto-import-secret

---

Makefile.prow
controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_test.go

https://github.com/stolostron/backlog/issues/24206

refactor scheduleOwnsLatestStorageBackups

---

api/v1beta1/restore_types.go
controllers/restore_controller_test.go
controllers/restore_post.go
controllers/restore_post_test.go
controllers/restore_test.go

https://github.com/stolostron/backlog/issues/26410
CleanupAll for credentials

cleanup all restore option for credentials

---

controllers/restore_post_test.go

https://github.com/stolostron/backlog/issues/26410

add back configMap tests

---

Makefile.prow

increase tests timeout

---

controllers/pre_backup.go

https://github.com/stolostron/backlog/issues/26385#issuecomment-1282934513

don't backup MSA addon

---

Dockerfile
go.mod

https://github.com/stolostron/backlog/issues/26029

Update to golang 1.19 ACM 2.7

---

controllers/pre_backup.go
controllers/schedule.go
controllers/schedule_controller_test.go
controllers/utils.go

https://issues.redhat.com/browse/ACM-1907
https://issues.redhat.com/browse/ACM-1886
Call cleanupMSAForImportedClusters when MCE disables MSA

delete MSA CR when MSA disabled

---

controllers/pre_backup.go
controllers/restore_controller.go
controllers/restore_post.go
controllers/restore_post_test.go
controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_test.go

Initialize the CRD mapper once on reconcile

create crd mapper once

---

controllers/backup.go
controllers/pre_backup.go
controllers/pre_backup_test.go
controllers/restore.go
controllers/restore_post_test.go

refactor unused code

---

controllers/restore_post.go
controllers/schedule.go
controllers/schedule_test.go

https://github.com/stolostron/backlog/issues/23681
- Add more logging for postRestoreActivation
- update some tests

improve messages for post restore op

---

controllers/backup.go

https://issues.redhat.com/browse/ACM-1931

backup clusterdeployment first

---

README.md
config/samples/cluster_v1beta1_restore_passive.yaml
config/samples/cluster_v1beta1_restore_passive_sync.yaml
controllers/backup.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go
controllers/suite_test.go

https://github.com/stolostron/backlog/issues/26542

2.6 move hive managed clusters under activation phase

---

api/v1beta1/groupversion_info.go
controllers/backup.go
controllers/create_helper.go
controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go
controllers/schedule_test.go
controllers/utils.go
controllers/utils_test.go

https://github.com/stolostron/backlog/issues/26575

Update Velero schedule resources if changed

---

README.md

https://issues.redhat.com/browse/ACM-2074

document using the same MCH MCE settings

---

controllers/backup.go
controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_test.go

https://github.com/stolostron/backlog/issues/26765

Update velero schedules specs based on backupschedule spec

---

controllers/pre_backup.go

https://issues.redhat.com/browse/ACM-2074
Don't exclude MSA and MSA addon from backup

backup MSA and MSA addon

---

controllers/restore.go
controllers/restore_post.go

https://github.com/stolostron/backlog/issues/26911

Annotate auto import secret with keep annotation

---

config/crd/bases/velero.io_restores.yaml

https://github.com/stolostron/backlog/issues/26912

update velero crds to v1.9.1

---

controllers/backup.go

https://issues.redhat.com/browse/ACM-2288

backup clusterimageset

---

Dockerfile
go.mod

https://github.com/stolostron/backlog/issues/26086

update release 2.5 to go 1.19

---

controllers/backup_test.go
controllers/pre_backup.go

2.7 PR https://github.com/stolostron/cluster-backup-operator/pull/376
https://issues.redhat.com/browse/ACM-2327
Reported issue
1. On prim hub, create clusterpool + claim a managed cluster >> OK
2. Hibernate the managed cluster claimed in step 1
3. Create backup schedule >> backups created successfully
4. Shutdown prim hub, run restore activation on second hub
5. Managed cluster restored on second hub in hibernating state
6. Resume the hibernating managed cluster in step 5
Actual results:
The resumed managed cluster is stuck at 'Pending import'
When we backup a cluster, we should not backup its import secret, we should let import controller create it in the new hub

rel 2.6 do not backup hive secrets

---

controllers/schedule.go
controllers/schedule_test.go

2.7 PR https://github.com/stolostron/cluster-backup-operator/pull/376
https://issues.redhat.com/browse/ACM-2327
Reported issue
1. On prim hub, create clusterpool + claim a managed cluster >> OK
2. Hibernate the managed cluster claimed in step 1
3. Create backup schedule >> backups created successfully
4. Shutdown prim hub, run restore activation on second hub
5. Managed cluster restored on second hub in hibernating state
6. Resume the hibernating managed cluster in step 5
Actual results:
The resumed managed cluster is stuck at 'Pending import'

2.5 - don't backup hive import secrets

---

Dockerfile

Fix security hotspot 
issue: Copying recursively might inadvertently add sensitive data to the container. Make sure it is safe here.
Dockerfile 
COPY . . command
https://issues.redhat.com/browse/ACM-4488

update docker copy command

---

main.go

For: https://issues.redhat.com/browse/ACM-4767
Cmd line flags:
- --lease-duration
- --renew-deadline
- --retry-period

cmd line flags for leader election settings

---

config/crd/bases/velero.io_backups.yaml
config/crd/bases/velero.io_restores.yaml
config/crd/bases/velero.io_schedules.yaml

This reverts commit a839875d81e055e96d70d5fbdecdd1efd084450e.
Fixing https://issues.redhat.com/browse/ACM-6997

Revert "Update Velero CRDs based on OADP 1.2 (#416)"

---

Dockerfile
go.mod

(cherry picked from commit 835350c1e79a44b5833a84e0326f6c016f021aa2)

Update upstream to golang 1.20 (#427)

---

README.md

Jira https://issues.redhat.com/browse/ACM-7851

Update managedServiceAccountTTL section in project readme

---

controllers/backup.go

Jira https://issues.redhat.com/browse/MGMT-16119

Remove baremetalhost.metal3.io from backup

---

controllers/restore.go
controllers/restore_controller.go
controllers/restore_test.go

https://issues.redhat.com/browse/ACM-8857
Create velero Restore for credentials first
Create ManagedClusters restore last
Resources restored after credentials
Then managed clusters

restore creds first , managed clusters last

---

controllers/restore_controller.go

Jira https://issues.redhat.com/browse/ACM-9683

Log create restore error

---

README.md
controllers/backup.go

Jira: https://issues.redhat.com/browse/ACM-10638

Remove managedcluster.clusterview.open-cluster-management.io from Backup

---

api/v1beta1/restore_types.go
api/v1beta1/schedule_types.go
config/crd/bases/cluster.open-cluster-management.io_backupschedules.yaml
config/crd/bases/cluster.open-cluster-management.io_restores.yaml

Jira https://issues.redhat.com/browse/ACM-8975

Update API descriptions

---

controllers/restore_controller.go

https://issues.redhat.com/browse/ACM-11926
Issue : 
The auto import operation doesn't work ( is run too early ) when the cleanupBeforeRestore is set to None on the acm restore resource.  The auto import may also not complete properly if the cleanupBeforeRestore is set to CleanupRestore but the clean up  operation is completed before the managed clusters backup is fully restored.
Workaround:
- create the acm restore acm-restore resource and wait for all velero restore resources to show as completed ( cleanupBeforeRestore can be set to None or CleanupRestore ) 
- delete the acm-restore resource
- create a new resource ( same name, or different ); since all resources are already restored, the post restore operation which runs the auto import of the managed clusters will be able to complete …

refresh restore list when checking overall status ( https://issues.redhat.com/browse/ACM-11926 )

---

controllers/restore_controller_test.go

- to test restore reconcile - previously there could be a timing issue (see PR:
https://github.com/stolostron/cluster-backup-operator/pull/547)
- Before the above PR, this test would fail approximately 4 out of 5 attempts

Some unit test updates

---

README.md

https://issues.redhat.com/browse/ACM-11855

ACM-11855 - Update OADP channel validation in README

---

controllers/pre_backup.go

extra logging for debugging msa ManagedClusterAddOn creation

logging in pre-backup for MSA mgdclusteraddon gen

---

hack/crds/velero.io_backups.yaml
hack/crds/velero.io_backupstoragelocations.yaml
hack/crds/velero.io_deletebackuprequests.yaml
hack/crds/velero.io_restores.yaml
hack/crds/velero.io_schedules.yaml

Updated Velero CRDs for OADP 1.4: https://github.com/openshift/oadp-operator/tree/oadp-1.4/bundle/manifests

ACM-11659 - Update Velero CRDs for OADP 1.4

---

config/samples/cluster_v1beta1_restore_status.yaml

Jira https://issues.redhat.com/browse/ACM-12708

ACM-12708 - Add a sample using restoreStatus

---

README.md

https://issues.redhat.com/browse/ACM-11857

ACM-11857 - Add OADP version relationship to the readme

---

config/samples/usecases/move-all-clusters/move-all-managed-clusters.yaml
config/samples/usecases/move-clusters/move-managed-clusters-step0.yaml
config/samples/usecases/move-clusters/move-managed-clusters-step1.yaml
config/samples/usecases/move-clusters/move-managed-clusters-step2.yaml

https://issues.redhat.com/browse/ACM-13530

add samples for moving clusters to another hub

---

config/samples/usecases/move-all-clusters/move-all-managed-clusters.yaml
config/samples/usecases/move-clusters/move-managed-clusters-step0.yaml
config/samples/usecases/move-clusters/move-managed-clusters-step1.yaml
config/samples/usecases/move-clusters/move-managed-clusters-step2.yaml

Update samples readme 
https://issues.redhat.com/browse/ACM-13530

update readme for samples

---

controllers/restore_post.go

- we just ignore these, but need not to fail
Fixes: https://issues.redhat.com/browse/ACM-13692

err handling when dynamic resource is not listable - For: https://issues.redhat.com/browse/ACM-13692

---

README.md

https://issues.redhat.com/browse/ACM-14156
Update readme to document what ACM versions support OADP update using MCH annotation

doc oadp version annotation

---

README.md

Jira: https://issues.redhat.com/browse/ACM-11859

ACM-11859 - Include the performance data tested in a large-scale environment

---

config/samples/usecases/move-clusters/move-managed-clusters-step0.yaml

Changes:
- Update step0 sample to include any activation resources created by the user, if the user moves hub resources with the managed clusters
- Update readme to mark step0 as optional

mark step0 optional and update step0 restore filter

---

.tekton/cluster-backup-operator-acm-213-pull-request.yaml
.tekton/cluster-backup-operator-acm-213-push.yaml

This PR:
- Update konflux CEL from release-2.13 to main

:seedling: [main] update konflux files

---

.tekton/cluster-backup-operator-acm-213-pull-request.yaml
.tekton/cluster-backup-operator-acm-213-push.yaml
Dockerfile
go.mod

https://issues.redhat.com/browse/ACM-17268

ACM-17268 - Update to Go 1.23

---

go.mod

(cherry picked from commit 7c26cd6017baa63cede9b505ec762570821f0d03)

[release-2.10] Remove obsolete dep github.com/ulikunitz/xz (#888)

---

go.mod

(cherry picked from commit 7c26cd6017baa63cede9b505ec762570821f0d03)

[release-2.11] Remove obsolete dep github.com/ulikunitz/xz (#888)

---

go.mod
go.sum

golang.org/x/oauth2 to v0.28.0

---

Dockerfile.rhtap

https://issues.redhat.com/browse/ACM-19665

[release-2.12] https://issues.redhat.com/browse/ACM-19665 - FIPS and ARCH related changes

---

.tekton/cluster-backup-operator-acm-213-pull-request.yaml
.tekton/cluster-backup-operator-acm-213-push.yaml

https://issues.redhat.com/browse/KONFLUX-2264

[release-2.13] Add shell and unicode sast pipeline tasks

---

README.md

https://issues.redhat.com/browse/ACM-19098

Document VM Backup and Restore Performance Using Policies

---

.tekton/cluster-backup-operator-acm-212-pull-request.yaml
.tekton/cluster-backup-operator-acm-212-push.yaml
Dockerfile.rhtap

- will be required for the enterprise contract
(cherry picked from commit 1d85b9519398e8546a576af9a593cf149487081f)

konflux - enable hermetic & build-source-image (

---

.tekton/cluster-backup-operator-acm-212-push.yaml

(cherry picked from commit b5efa7de0ace513486e650a0cddf41361c30c883)

[release-2.12] konflux enable multi-arch on push pipeline only (#1009)

---

go.mod
go.sum

| Package | Type | Update | Change |
|---|---|---|---|
| [github.com/prometheus/common](https://redirect.github.com/prometheus/common) | indirect | minor | `v0.62.0` -> `v0.64.0` |

update module github.com/prometheus/common to v0.64.0

---

go.mod
go.sum

| Package | Type | Update | Change |
|---|---|---|---|
| [github.com/prometheus/procfs](https://redirect.github.com/prometheus/procfs) | indirect | minor | `v0.15.1` -> `v0.16.1` |

update module github.com/prometheus/procfs to v0.16.1

---

.github/renovate.json

For:
https://issues.redhat.com/browse/ACM-23483
https://issues.redhat.com/browse/ACM-23482
https://issues.redhat.com/browse/ACM-23481
https://issues.redhat.com/browse/ACM-23480

renovate -update for dockerfile pinning and grouping docker img updates

---

OWNERS

Even though I am added on the main branch, on the other branches, where this cherry-picked commit was not introduced, I dont have permissions to approve PRs

Add falconizmi to OWNERS on branch release-2.13

---

OWNERS

(cherry picked from commit 4a11b73b885df1f184ec2a32286ce69559d67bd2)
Even though I am added on the main branch, on the other branches, where this cherry-picked commit was not introduced, I dont have permissions to approve PRs

Add falconizmi to OWNERS on branch release-2.14

---

config/default/manager_auth_proxy_patch.yaml
config/default/manager_config_patch.yaml
config/manager/manager.yaml
config/rbac/service_account.yaml

https://issues.redhat.com/browse/ACM-24642
**SonarQube security issue: _Bind this Service Account to RBAC or disable "automountServiceAccountToken"_**
Fixed the SonarQube security warning about service account permissions:
- config/rbac/service_account.yaml ✅ - Added automountServiceAccountToken: true to the ServiceAccount resource
- config/manager/manager.yaml ✅ - Added automountServiceAccountToken: true to the deployment pod spec
- config/default/manager_config_patch.yaml ✅ - Added automountServiceAccountToken: true to the patch pod spec
The fix ensures:
Service account tokens are explicitly mounted (not just defaulted)
The controller retains all necessary permissions to function
SonarQube security compliance requirements are met
No functionality is broken
**SonarQube security issue: …

[AI-assisted] fix sonar security issues

---

config/default/manager_auth_proxy_patch.yaml
config/default/manager_config_patch.yaml
config/manager/manager.yaml
config/rbac/service_account.yaml

This reverts commit f8e7e8a6a35a2fa9b94663550931cfe8bb5418f4.

Revert "[AI-assisted] fix sonar security issues (#1417)"
