Makefile.prow

Signed-off-by: Joshua Packer <jpacker@redhat.com>
* Disables the generator call in `make test` so that prow can call `make unit-tests`
* Activates a `make unit-tests`

Activate short test

---

PROJECT

Currently `operator-sdk`  or `kubebuilder`, whatever you use,  is lost due to mismatch between PROJECT file and the rest of codebase.
If we want to implement a `webhook` we need this to be fixed.

to fix operator-sdk issue

---

controllers/backup.go
controllers/backup_controller.go
controllers/backup_controller_test.go
controllers/backup_test.go
controllers/restore.go
controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/restore_test.go
controllers/suite_test.go
controllers/utils.go
go.mod
main.go

Hi all, I'm proposing to fix which basically it's a `sed s/open-cluster-management-io/open-cluster-management/g`. I'm not 100% positive about this but the rule (if any) it's not crystal clear (to me).
May you have a look and (if rejected) explain the rationale? Thanks

move GH domain to open-cluster-management/

---

README.md

- Updated Readme to explain the output of a Backup and Restore operation
- Added more info and links for the Velero and OADP op
- document that op resources must be in the same ns with the OADP operator
- updated oc get commands to replace -A with oadp ns
https://github.com/open-cluster-management/backlog/issues/15698

update readme with execution details

---

config/rbac/role.yaml
controllers/backup.go
controllers/backup_controller.go

Fix https://github.com/open-cluster-management/backlog/issues/15746
Picked up the latest crd updates for schedule resource and included the fix from PR https://github.com/open-cluster-management/cluster-backup-operator/pull/24
I found it easier to create a new PR and add #24 on top of the latest then to push all schedule changes in that PR
With these changes, the controller starts successfully
The velero.io CRDs have been created prior to this step ( OADP Operator was installed )
```
vbirsan@redhat:cluster-backup-operator-2 vbirsan$ oc logs cluster-backup-operator-controller-manager-5d5fc5d9dc-gzj5f -n cluster-backup-operator-system -c manager
I0901 17:47:53.567238       1 request.go:655] Throttling request took 1.048109819s, request: …
```

create watch rules for channel and managedcluster crd

---

api/v1beta1/schedule_types.go
config/crd/bases/cluster.open-cluster-management.io_backupschedules.yaml
config/samples/cluster_v1beta1_backupschedule.yaml
controllers/schedule_controller_test.go

- On Schedule resource, make veleroTTL optional ( backups never expire if option not set )
- On the backupSchedule sample yaml, replace schedule name, frpm `backup-schedule-acm` to `schedule-acm` ( name is a bit too long after adding backup type prefix )
Schedule names are now

make backups TTL optional

---

README.md
api/v1beta1/schedule_types.go
config/crd/bases/cluster.open-cluster-management.io_backupschedules.yaml
config/samples/cluster_v1beta1_backupschedule.yaml
controllers/backup.go
controllers/backup_controller.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go

Changes:
- add required property maxBackups to backupschedule resource
```
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: BackupSchedule
metadata:
name: schedule-acm
spec:
maxBackups: 10 # maximum number of backups after which old backups should be removed
veleroSchedule: 0 */6 * * * # Create a backup every 6 hours
veleroTtl: 72h # deletes scheduled backups after 72h; optional, backups never expire if option not set
```
- updated readme to add the backupschedule resource and remove references to the backup ( we will keep only the backupschedule )

add maxBackups to backupschedule operator

---

controllers/schedule.go

If the velero pod is in error or the Velero resource was not created, schedules have no status
Add extra details for troubleshooting

add debug details when schedule has no status

---

controllers/restore.go
controllers/restore_controller.go

https://github.com/open-cluster-management/backlog/issues/15943
- Fix gosec:G601 vulnerability based on 
https://stackoverflow.com/questions/62446118/implicit-memory-aliasing-in-for-loop
- Fix gosec:G101 
```
When a specific false positive has been identified and verified as safe, you may wish to suppress only that single rule (or a specific set of rules) within a section of code, while continuing to scan for other problems. To do this, you can list the rule(s) to be suppressed within the #nosec annotation, e.g: /* #nosec G401 */ or // #nosec G201 G202 G203
```

fix sonar vulnerabilities

---

controllers/backup.go

fix typo on argocd res names

---

api/v1beta1/restore_types.go
config/crd/bases/cluster.open-cluster-management.io_restores.yaml
controllers/backup.go
controllers/schedule_controller.go

related to https://github.com/open-cluster-management/backlog/issues/16310
Changes:
- when getting the list of old backups, filter in only the ones generated by the acm scheduler; backups with names

check only existing backups created by the acm schedule

---

README.md

Update readme to document that restore op can be executed only once
fyi @thuyn-581 
https://github.com/open-cluster-management/backlog/issues/16170

restore op can be executed once

---

api/v1beta1/schedule_types.go
config/crd/bases/cluster.open-cluster-management.io_backupschedules.yaml
config/samples/cluster_v1beta1_backupschedule.yaml

Update ttl description : If not specified the maximum default value set by velero is used - 720h

update ttl description

---

controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/schedule_controller.go

https://github.com/open-cluster-management/backlog/issues/16526
Changes:
- verify if the velero storageLocation object is in the same ns with the backup or restore operator resources
- show an error if they are not in the same namespace ; in the log and the resource status
- updated restore tests

check if restore resource is in the velero ns

---

controllers/backup.go

Backup helmrelease objects, excluding namespaces : local-cluster and acm ns
https://github.com/open-cluster-management/backlog/issues/16817

backup apps helm releases

---

controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go

1. Check if BackupStoargeLocation is valid based on the logic suggested here: https://github.com/open-cluster-management/cluster-backup-operator/pull/67#discussion_r722448653
- get the list of the storagelocations
- get only the resources with an onwerReference not null and Kind Velero
2.  Make sure the resource is created in the namespace of the valid BackupStorageLocation

Check if BackupStorageLocation is valid

---

config/samples/cluster_v1beta1_restore_passive.yaml
config/samples/restore-acm-passive-activate.yaml
controllers/backup.go
controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go

https://github.com/open-cluster-management/backlog/issues/18199
Related to 
https://issues.redhat.com/projects/ACM/issues/ACM-1001
Changes: 
- updated managed cluster backup to include only resources used by backup; as tested , only this is needed to backup remote clusters : 
= to show the clusters as detached ( not try to connect to the new hub )
"ClusterDeployment",
"MachinePool",
"ClusterSyncLease",
"ClusterSync",
Secrets with this label: "hive.openshift.io/secret-type"
= to activate the clusters ( activation data )
"ManagedCluster.cluster.open-cluster-management.io", //global
"KlusterletAddonConfig",
"ManagedClusterAddon",
"ManagedClusterInfo",
"ManagedClusterSet",
"ManagedClusterSetBindings",
"ClusterPool",
"ClusterCurator", …

refactor backup content

---

controllers/backup.go

related to https://github.com/open-cluster-management/backlog/issues/18200
Removing resources not needing to be backed up ; they are recreated on the new hub by owning resources
"hiveinternal.openshift.io/v1alpha1": [
"clustersync",
"clustersynclease"
],
"internal.open-cluster-management.io/v1beta1": [
"managedclusterinfo"
],

remove from backup internal resources

---

config/samples/cluster_v1beta1_backupschedule.yaml
config/samples/cluster_v1beta1_restore_passive.yaml
config/samples/cluster_v1beta1_restore_passive_activate.yaml
config/samples/kustomization.yaml
controllers/backup.go
controllers/backup_test.go
controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go
controllers/utils.go

https://github.com/open-cluster-management/backlog/issues/18200
Changes:
- Create a new resources backup for resources with label `cluster.open-cluster-management.io/backup`
```
spec:
defaultVolumesToRestic: false
excludedResources:
- secret
hooks: {}
includeClusterResources: true
labelSelector:
matchExpressions:
- key: cluster.open-cluster-management.io/backup
operator: Exists
```
- sort schedule names to create first the credentials schedules, then clusters, last resources
- updated the tests to use len(veleroScheduleNames) instead of 3-6
- updated this tests - acm backupschedules confused with velero schedules
```
// count ACM ( NOT velero) schedules, should be still just 5
// this nb is NOT the nb of velero backup schedules created from
// the acm backupschdule object ( which is …
```

create generic resources backup

---

controllers/backup_test.go
controllers/restore_controller_test.go
controllers/schedule_controller_test.go
controllers/suite_test.go
go.mod
go.sum

Followed the steps here https://onsi.github.io/ginkgo/MIGRATING_TO_V2 for upgrading to Ginkgo 2.0
https://github.com/stolostron/backlog/issues/18945

Migrate testing framework to Ginkgo 2.0

---

api/v1beta1/restore_types.go
config/crd/bases/cluster.open-cluster-management.io_restores.yaml
config/samples/cluster_v1beta1_restore.yaml
config/samples/cluster_v1beta1_restore_passive.yaml
controllers/backup.go
controllers/restore.go
controllers/restore_controller.go
controllers/schedule_controller_test.go
controllers/utils.go
main.go

Add an optional spec property on restore to allow cleaning up resources before restoring again
`cleanupBeforeRestore` - optional, if not define is set to false ( need more testing before being confident this is working in all cases and not breaking anything )
If cleanupBeforeRestore = true, for each restore file , prior to creating the velero.io.Restore ( so calling the actual restore ) we call a routine which cleans up all resources defined by the restore's backup definition ; resources must have the label `velero.io/backup-name` so they should have been created by another restore. All other resources are kept as is
We need to test resources with finalizers or owned by other resources
For example ClusterDeployment - which I think I …

clean up resources before restore

---

controllers/backup.go

Link to conversations :
https://github.com/stolostron/backlog/issues/18514#issuecomment-1006051587
https://github.com/stolostron/backlog/issues/19209#issuecomment-1036245857
Changes : 
- add `search.open-cluster-management.io api` to the. excluded api group; this will make any of the CRDs from `search.open-cluster-management.io api` to not be considered for the acm-resources backup
- since the CRD is not in the `acm-resources` if any CR in this group is tagged with the `cluster.open-cluster-management.io/backup` , they will be picked up by the acm-resources-generic backup, used to get third parties CRDs 
Why we have to specifically remove the `search.open-cluster-management.io api` from this backup ?
- Any resource included in the …

exclude search.open-cluster-management.io api group

---

controllers/backup.go
controllers/restore.go
controllers/schedule_controller_test.go
controllers/suite_test.go
controllers/utils.go

Changes: 
- Before restore is called clean up any resource with a label `cluster.open-cluster-management.io/backup` and `velero.io/backup-name` ( created by another restore )
- exclude `local-cluster` NS from managed cluster resources
- use api group for backupManagedClusterResources list

clean up generic resources

---

config/samples/cluster_v1beta1_restore.yaml
config/samples/cluster_v1beta1_restore_passive.yaml
config/samples/cluster_v1beta1_restore_passive_activate.yaml

update samples to clean up previously restored resources 
`veleroManagedClustersBackupName: true` asks to delete all resources with a velero-name label , which are resources created by a previous backup
We want to clean up before restoring again
This should address resources updated after the previous backup was run or resources delete since then

enable cleanup resources by default

---

api/v1beta1/schedule_types.go
controllers/backup.go
controllers/restore_controller.go
controllers/schedule.go
controllers/schedule_controller.go
controllers/suite_test.go
controllers/utils.go
main.go

https://github.com/stolostron/backlog/issues/19469
Changes 
1. introduce a new backup status `SchedulePhaseBackupCollision`
2. annotate all backup schedules with the current cluster ID ( use `ClusterVersion` uid ) 
```
// BackupScheduleClusterUIDLabel is the label key used to identify the cluster id that generated the backup
BackupScheduleClusterLabel string = "cluster.open-cluster-management.io/backup-cluster"
```
sample labels 
```
labels:
cluster.open-cluster-management.io/backup-cluster: 86941453-3823-4f03-8bdd-082297d32129 <<<<<<
cluster.open-cluster-management.io/backup-schedule-name: schedule-acm
cluster.open-cluster-management.io/backup-schedule-type: credentialsCluster
```
3. when creating a new acm backupscehdule, label velero io schedules with the above label
4. on reconcile, …

label backups with cluster id and check for collisions

---

controllers/schedule.go
controllers/schedule_controller.go

https://github.com/stolostron/backlog/issues/19469
If a backup finds a collision ( there is another schedule, from another cluster, that created more recent backups ) than the current backup will delete its schedules so that it doesn't write over the other backups.
The admin should verify which cluster must be the valid primary writing backups and decide which schedule to use

delete schedules on collision

---

controllers/schedule_controller.go

https://github.com/stolostron/backlog/issues/19469
When the backupschedule is first created, the state could be empty or New
For these 2 cases don't check on collision with other backups

allow schedule to get through when phase is empty

---

controllers/restore.go
controllers/restore_controller.go

Don't run a resources clean up when restoring managed cluster data
This could affect the cluster lifecycle; we also need to make sure we don't touch the local-cluster which is a global resource packaged with the acm-managed-clusters backup
https://github.com/stolostron/backlog/issues/19928

do not cleanup managed cluster resources

---

README.md
config/samples/cluster_v1beta1_backupschedule.yaml
controllers/restore.go
controllers/schedule_controller.go

Updates
- when checking for backup collision check if the velero schedules for this backup were created in the last few minutes, in this case skip the collision validation, this is a new backup created by the user
- update readme 
- update backup sample ttl to 3days; the cron jobs runs every 2h so more then 3 days will get too many backups
- when deleting resources on cleanup log patching finalizers; run finalizers only if delete has no errors

backup collision fixes

---

controllers/backup.go
controllers/restore_controller.go
controllers/schedule.go
controllers/schedule_controller.go

https://github.com/stolostron/backlog/issues/19776
Design: 
- create a dummy backup which sets the TTL to be the backup schedule cron job + 5 min
- this dummy backup (acm-validation-policy-schedule) will delete itself 5 min after the owner backup would start a new set of backups
- if the owner backup no longer creates backups, then after the last deletion there will be no acm-validation-policy-schedule backup in the storage location
- if there are no backupschedules writing backups at that storage location then there are going to be no acm-validation-policy-schedule backups ( they delete themself using the cron time )
- the policy checks for at least one instance of a acm-validation-policy-schedule backup at the storage location; if …

create a dummy backup for policy validation of enabled backups

---

README.md
controllers/backup.go
controllers/restore_controller.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go

https://github.com/stolostron/backlog/issues/19776
Delete expired acm-validation-policy-schedule backups
// clean up expired validation backups, workaround for
// velero doesn't delete expired backups if they are in FailedValidation
// or storage location is no longer valid
https://coreos.slack.com/archives/C0144ECKUJ0/p1646405908138569

delete expired backups and update readme

---

controllers/schedule_controller.go

The index of backup schedule names were changed after ValidationSchedule was added

Fix the index of backup schedule names in the swap after sorting them

---

README.md
controllers/backup.go
controllers/restore.go
controllers/restore_controller.go
controllers/schedule_controller.go

https://github.com/stolostron/backlog/issues/20486
backup should allow third party to backup generic resources under activation data
Changes :
- introduced a new value for for the backup label to allow restroring resources in the activation phase
when you add the `cluster.open-cluster-management.io/backup` label to a resource, this resource is automatically backed up under the `acm-resources-generic-schedule` backup. If any of these resources need to be restored only when the managed clusters are moved to the new hub, so when the `veleroManagedClustersBackupName:latest` is used on the restored resource, then you have to set the label value to `cluster-activation`. This will ensure the resource is not restored unless the managed cluster activation is called.
Example :
```yaml
apiVersion: …
```

generic resources restored in activation phase

---

controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/utils.go

- When backup name is set in restore resource (for example veleroCredentialsBackupName: acm-credentials-schedule-20220309134806 for the following case), for CredentialsHive, CredentialsCluster, ResourcesGeneric types, try to find a backup with StartTimestamp within 30 seconds of the timestamp suffix in the requested backup name.
Note: For the following test case, the difference between the StartTimestamp of CredentialsHive backup and the target timestamp suffix in Credential backup name was 30 seconds even though based on their name it was expected to be 6 seconds.
[acm-credentials-hive-schedule-20220309134800]
[acm-credentials-schedule-20220309134806]
- Fixes a bug and its unit test, when calling retrieveRestoreDetails, if error, return error …

Look for backups within a time range when backup name is set

---

controllers/backup.go
controllers/restore.go
controllers/schedule_controller.go
controllers/suite_test.go

https://github.com/stolostron/backlog/issues/20857
Changes:
- include clusterimageset, hiveconfig but don't clean them up
- exclude cluster-backup NS
- exclude from cleanup any resource with a label of installer.name=multiclusterhub ( in case there are other charts installed by MCH in a separate ns then the MCH )
- exclude from cleanup resources with velero.io/exclude-from-backup=true, they are not backed up

exclude cluster-backup NS

---

controllers/backup.go

https://github.com/stolostron/backlog/issues/20903
The following resources will be backup up by default
agents                                                               agent-install.openshift.io                     true         Agent
agentserviceconfigs                                                  agent-install.openshift.io                     false        AgentServiceConfig
infraenvs                                                            agent-install.openshift.io                     true         InfraEnv
nmstateconfigs                                                       agent-install.openshift.io                     true         NMStateConfig

backup CR from agent-install.openshift.io group

---

controllers/restore.go
controllers/restore_controller.go

Changes: 
- fix the patch call for deleting finalizers for global objects
- clean up managed cluster resources when restoring just resources ; they need to be cleaned up to match a passive config, will be added when the managed clusters are restored

fix finalizers patch for global resources

---

controllers/restore.go
controllers/restore_controller.go

https://github.com/stolostron/backlog/issues/20944
Changes:
- show message info if the sync options are not valid and the `syncRestoreWithNewBackups` prop is ignored
- allow updating the `veleroManagedClustersBackupName` to latest and restore managed clusters

allow restoring managed clusters on sync

---

README.md
controllers/restore.go
controllers/restore_controller.go

https://github.com/stolostron/backlog/issues/21170
Changes:
- allow restore to run to completion even if the cleanup returned failures. If we don't do that, we can clean up previous restored resources and not add them back
- add more restore events, to follow the flow; example output
- update readme to document the restore events
```
oc describe restore -n open-cluster-management-backup example
Name:         example
Namespace:    open-cluster-management-backup
Labels:       <none>
Annotations:  <none>
API Version:  cluster.open-cluster-management.io/v1beta1
Kind:         Restore
Metadata:
Creation Timestamp:  2022-03-26T19:44:49Z
Generation:          1
Managed Fields:
API Version:  cluster.open-cluster-management.io/v1beta1
Fields Type: …
```

execute restore if cleanup fails; add more events

---

controllers/restore_controller.go
controllers/restore_controller_test.go

Fixes the status phase update when syncRestoreWithNewBackups is updated from true to false, in this case the sync should stop and the phase should update from Enabled to Finished/FinishedWithErrors

Fix the phase update when sync is set to disabled

---

README.md
controllers/restore.go
controllers/restore_controller.go

- Updated restore events to remove the message for looking on new backups; the events are grouped together and the result is not helpful. It also generates a lot of messages ( ie every 20min if your are syncing every 20 min )
- updated events message 
Output removed 
```
Normal  Processing restore request                             11m (x10 over 138m)  Restore controller  Restore sync found new backups
Normal  Processing restore request                             95s (x16 over 133m)  Restore controller  Restore sync found no new backups
```
Current output 
```
Status:
Last Message:                     Velero restores have run to completion, restore will continue to sync with new backups
Phase:                            Enabled
Velero …
```

update events on restore

---

controllers/backup.go

https://github.com/stolostron/backlog/issues/21499
Changes: 
- backup only baremetalhost.metal3.io from the metal3.io group
- move it under activation data; it seems that the hosts, once restore, try to power on
- skipped the `Provisioning.metal3.io` CR because one is already created on the restore cluster; unless you restore with the option CleanupAll, the Provisioning is not restored from the backup. I don't think replacing the existing is not going to break something

backup baremetalhost.metal3.io under activation data

---

controllers/backup.go
controllers/schedule.go

https://github.com/stolostron/backlog/issues/21499
Changes:
- backup [baremetalhost.metal3.io](http://baremetalhost.metal3.io/)
- exclude resources from  openshift-machine-api NS
- backup the baremetalhost under the managedclusters ( activation data )

exclude baremetalhost.metal3 from openshift-machine-api ns

---

controllers/restore.go
controllers/restore_controller.go

https://github.com/stolostron/backlog/issues/21478
- Fix sync to check if either new resources backup or new credential backup is available to sync with (used to look for new resources backup only)
- Fix creating Velero restore code not to return error in case the resource already exists (may happen in sync case only)
- Fix cleanup code to skip cleanup if Velero restore already exists and skip ResourcesGeneric cleanup in sync activation case (fix for duplicate cleanups in activation process)

Fixes for restore sync

---

controllers/backup.go
controllers/restore_controller.go

https://github.com/stolostron/backlog/issues/21499
Based on slack comments https://coreos.slack.com/archives/C01LZ5SBLLQ/p1649364957767159?thread_ts=1646903746.296189&cid=C01LZ5SBLLQ 
BMCEventSubscription and HostFirmwareSettings need to be backed up

backup BMCEventSubscription and HostFirmwareSettings

---

controllers/backup.go

https://github.com/stolostron/backlog/issues/21018
Issue : 
Most of the hive controllers will ignore a CD with no associated ClusterSync object
There's no ClusterSync object initially because it's a hiveinternal CR and the backup has been ignoring those (which should be the right thing theoretically / long-term, but read on...)
The ClusterSync controller refuses to create a ClusterSync object for an unreachable cluster.
Fix: 
Add ClusterSync to the backup data so that hibernating clusters CD are being processed by the hive controllers

backup clustersync with the managed clusters backup

---

controllers/restore.go

related to https://github.com/stolostron/backlog/issues/22236
As we were testing the appset deployment on local cluster, we observed that restored applications were not placed on local cluster, new hub
The appset uses the new placement rule which requires setting the managedcluster set , which in turn is configured to use namespace bindings
The root cause : 
The `default` managedclusterset is created automatically when ACM creates the local-cluster; so this resource exists on the passive hub and was not created by a previous restore
When we restore the data, we use the option `cleanupBeforeRestore: CleanupRestored` which doesn't clean up the `default` managedclusterset ( since it was not created by a restore ); so the default …

cleanup managedclustersets

---

controllers/backup.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go

With the exception of the secrets and configmaps which are backed up by the credentials schedule, all other resources having the `cluster.open-cluster-management.io/backup-cluster` should be backed up under the acm-resources-generic-schedule schedule
https://github.com/stolostron/backlog/issues/22478

resources with backup label should always be backed up by the generic backup

---

controllers/pre_backup.go
controllers/schedule_controller.go

https://github.com/stolostron/backlog/issues/23876
Changes : 
- if backupschedule ttl time is set, use that for MSA validity; MSA validity = ttl * 3
- if backupschedule not set, use default 720h * 3

use backupSchedule ttl for MSA validity

---

config/crd/bases/cluster.open-cluster-management.io_backupschedules.yaml

We upgraded our Velero dependency from github.com/vmware-tanzu/velero v1.7.1 to github.com/vmware-tanzu/velero v1.9.0 in https://github.com/stolostron/cluster-backup-operator/pull/270, this includes an API change related to BackupSpec which defines the specification for a Velero backup. This change affects our BackupSchedule CRD.

Velero BackupSpec change in v1.9.0

---

controllers/pre_backup.go
controllers/pre_backup_test.go
controllers/schedule_controller_test.go

Changes:
- annotate MSA token with token lastRefreshTimestamp information. This is useful because the token might have been created after the MSA was created ( cluster is down at the time the MSA is created ) ; it is useful when the token refresh doesn't match the expected expiry time ( same scenario, the token should expire but since the cluster is not reachable the recycle cannot happen when the token is set to expire )
```
kind: Secret
apiVersion: v1
metadata:
annotations:
expirationTimestamp: '2022-07-27T18:52:13Z'
lastRefreshTimestamp: '2022-07-27T16:52:13Z'
```
- created a new MSA pair token when the initial token validity had passed half the expiration time; 
The logic : the initial MSA token is set to expire 2*backupTTL
Let's …

create pair MSA account

---

controllers/restore.go
controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/restore_test.go

- Fixed reporting of invalid cleanup value, it shows now
- restore should not execute if the cleanup option is invalid
```
kind: Restore
metadata:
name: example2
namespace: open-cluster-management-backup
spec:
cleanupBeforeRestore: aaaaaa
veleroCredentialsBackupName: latest
veleroManagedClustersBackupName: latest
veleroResourcesBackupName: latest
status:
lastMessage: 'invalid CleanupBeforeRestore value : aaaaaa'
phase: FinishedWithErrors
```

test coverage for cleanup option

---

controllers/schedule.go
controllers/schedule_test.go

Changes:
- when new schedules are created, generate new backups; this is the default behavior since we just moved to install oadp 1.1 in 2.7; which no longer creates backups on schedule creation
- you can disable the backup creation by setting `Spec.NoBackupOnStart=true` on the BackupSchedule CR

create backups when new schedule is created

---

controllers/restore.go
controllers/restore_test.go

related to https://github.com/stolostron/cluster-backup-operator/pull/313
If the backup doesn't create the hive and cluster creds backup ( with oadp 1.1 we group them in one backup ), restore looks for hive and cluster creds backup and finds ones that should not match the current backup
Change : look for those backups, for backward compatibility, but get the backups that matches the `acm-credentials-schedule` by start time and timestamp.

restore uses old hive cred backup whith oadp 1.1 orSelector

---

controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_test.go

related to https://github.com/stolostron/cluster-backup-operator/pull/313
With the number of backups reduced to 5, the swap should be updated

swap backups to have resources run last

---

controllers/restore.go
controllers/restore_controller.go
controllers/restore_test.go

Removed the clean up of resources before restore
The oadp 1.1 update of existing resources is enabled now
Need to implement a delete of delta resources, post restore, will do that in another pr

disable prepare for restore cleanup

---

controllers/restore_post.go
controllers/restore_post_test.go

Clean up managed cluster backup resources post restore; remove resources created by a previous restore which are no longer part of the latest restored backup
If managedClusters are not restored, clean up generic resources but with a label value not equal with cluster-activation
If managedClusters are restored, clean up all generic resources

process delta for restore clusters

---

README.md
config/samples/cluster_v1beta1_restore.yaml
config/samples/cluster_v1beta1_restore_passive.yaml
config/samples/cluster_v1beta1_restore_passive_activate.yaml
config/samples/cluster_v1beta1_restore_passive_sync.yaml
controllers/restore_post.go
controllers/restore_post_test.go

https://github.com/stolostron/backlog/issues/26192
Changes:
- removed doc around `CleanupAll` option, it should not be used
- updated readme to refer to post restore instead of pre restore
- do not run cleanup if option is `CleanupTypeNone`

dont run clean up if option is set to CleanupTypeNone

---

Makefile.prow
controllers/pre_backup.go
controllers/restore_controller.go
controllers/restore_post.go
controllers/restore_post_test.go
controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go
controllers/schedule_test.go
controllers/suite_test.go
main.go

https://github.com/stolostron/backlog/issues/24206#issuecomment-1279479335
Changes:
- reconcile after backupschedule failed validation due to the MSA option being invalid
- recreate the mapper on each reconcile
- remove mapper for restore reconciler, create one from discoveryInterface

fix CRD not picked up after pod is running

---

controllers/backup.go
controllers/pre_backup.go
controllers/pre_backup_test.go
controllers/restore_post.go
controllers/restore_post_test.go

https://github.com/stolostron/backlog/issues/26385
Don't backup MSA and manifest work
Before the MSA is created, delete any secrets with the same name ( if this is a passive - becoming active, there could be secrets created by the MSA on the initial primary; those secrets should be removed since this hub should enable MSA support before using the MSA feature; and creating new secrets with the same MSA won't work)

don't backup MSA and clean up secret on new backup

---

controllers/pre_backup.go
controllers/restore_controller.go
controllers/restore_post.go
controllers/restore_post_test.go

https://issues.redhat.com/browse/ACM-1886
Updated deleteDynamicResource function to allow deletion of resources with velero.io/exclude-from-backup

delete res with exclude label

---

controllers/create_helper.go
controllers/restore_post_test.go
controllers/restore_test.go
controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go
controllers/schedule_test.go
controllers/utils_test.go

Add tests for getSchedulesWithUpdatedResources
https://github.com/stolostron/backlog/issues/26765
https://github.com/stolostron/cluster-backup-operator/pull/362
Changes:
- refactor getSchedulesWithUpdatedResources 
- create new testcase for getSchedulesWithUpdatedResources
- update existing testcases to allow reconcile being called when the BackupSchedule ttl is changed

add tests for isVeleroSchedulesUpdateRequired

---

controllers/schedule_test.go

https://github.com/stolostron/cluster-backup-operator/pull/371
https://github.com/stolostron/backlog/issues/26765
https://github.com/stolostron/cluster-backup-operator/pull/362
Change:
Don't throw error if the update fails on last isVeleroSchedulesUpdateRequired test

fix isVeleroSchedulesUpdateRequired  test

---

controllers/pre_backup.go
controllers/pre_backup_test.go

https://issues.redhat.com/browse/ACM-2327
Reported issue
1. On prim hub, create clusterpool + claim a managed cluster >> OK
2. Hibernate the managed cluster claimed in step 1
3. Create backup schedule >> backups created successfully
4. Shutdown prim hub, run restore activation on second hub
5. Managed cluster restored on second hub in hibernating state
6. Resume the hibernating managed cluster in step 5
Actual results:
The resumed managed cluster is stuck at 'Pending import'
When we backup a cluster, we should not backup its import secret, we should let import controller create it in the new hub

don't backup hive import secrets

---

controllers/pre_backup.go

https://github.com/stolostron/backlog/issues/27027
Issue
Sometimes the MSA rolebinding is not lost on the managed cluster, even if the role still exists
Fix : attempt to  create the MSA manifest work on the hub even if the MSA addon exists

always attempt to create MSA manifest work

---

controllers/backup.go

It's been observed that since clusterimagesets are not backed up, the clusterpool(s) which use the custom imageset will not be able to scale/claim after restore activation.
Fix: add clusterimageset CR to backup
https://issues.redhat.com/browse/ACM-2288

backup clusterimageset in 2.6

---

controllers/pre_backup.go

https://issues.redhat.com/browse/ACM-2466
Issue:
managed-serviceaccount-import appliedmanifestwork left orphaned on managed cluster after detaching on restored hub
Version-Release number of selected component (if applicable):
How reproducible:
- On prim hub, enable cluster backup + managedserviceaccount in MCE
- Import an ocp cluster 
- Enable backup schedule >> backups created successfully
- Shutdown prim hub
- On second hub, run restore activation
- The imported cluster gets registered successfully to the second hub
- Detach the imported cluster on the second hub
Actual results:
managed-serviceaccount-import appliedmanifestwork left orphaned on managed cluster after being detached
Fix:
Backup the ManifestWork …

backup MSA ManifestWork

---

controllers/restore.go
controllers/restore_controller_test.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go
controllers/utils.go
controllers/utils_test.go

https://issues.redhat.com/browse/ACM-2505
- On ROSA hub, install ACM + enable backup
- Create DPA + backupstorage location >> OK
- Enable backup schedule
- Actual results:  Backup schedule failed
```
#oc get dpa -A
NAMESPACE                        NAME     AGE
open-cluster-management-backup   velero   6m3s
#oc get bsl -A
NAMESPACE                        NAME       PHASE       LAST VALIDATED   AGE     DEFAULT
open-cluster-management-backup   velero-1   Available   42s              6m16s   true
openshift-velero                 default    Available   11m              8d      true
#oc get bsch -A
NAMESPACE                        NAME           PHASE              MESSAGE
open-cluster-management-backup   schedule-acm …
```

look for BSL in the reconciled resource ns

---

config/samples/cluster_v1beta1_backupschedule.yaml
controllers/backup.go
controllers/schedule_controller_test.go
controllers/suite_test.go

Allow specifying the apiGroup for resources that need to be restored at activation time
backup agent installer as activation data resource 
Changes:
- introduced a new group includedActivationAPIGroupsByName , similar with includedAPIGroupsByName
- resources with the api groups which are part of the includedActivationAPIGroupsByName list will be stored under the acm-managed-clusters-schedule and will be restored at activation time, with the managed cluster resources
- moved the agent-install.openshift.io under this group

allow activation resources by group api

---

Makefile
Makefile.prow

- also set HOME only in build target inside Makefile.prow so it doesn't override for everything

use go install for getting build dependencies

---

controllers/pre_backup.go

https://issues.redhat.com/browse/ACM-4612
When enabling the automatic import feature, https://github.com/stolostron/cluster-backup-operator#enabling-the-automatic-import-feature, the controller creates a ManagedServiceAccount named auto-import-account and sets the token validity as defined by the BackupSchedule. 
At half time expiration, a new auto-import-account-pair is created to overlap with the initial auto-import-account so that if the initial token has expired when the backup is restored, the second token can be used ( it increases the probability that the auto-import-account part of the backup is valid at the time the backup is used )
The issue is that the ManifestWork for the  auto-import-account-pair was not created; so when the first token was invalid and the second was used …

create ManifestWork for auto-import-account-pair

---

controllers/pre_backup.go
controllers/pre_backup_test.go

https://issues.redhat.com/browse/ACM-4612
Addition to https://github.com/stolostron/cluster-backup-operator/pull/395
Issues:
- The pair manifest work gets created as soon as the initial MSA is created. It should only be created with the MSA pair
- The MSA pair is not cleaned up when BackupSchedule.Spec.UseManagedServiceAccount is set to false

fix creation of pair manifestwork and clean up of pair MSA

---

main.go

For: https://issues.redhat.com/browse/ACM-4767
Updating flags from previous PR - using standard examples from:  https://issues.redhat.com/browse/ACM-4108
Changed: flags are now using the standard names from the above examples and are now durations.

Update leader election flag names - use duration

---

api/v1beta1/restore_types.go
config/crd/bases/cluster.open-cluster-management.io_restores.yaml
controllers/create_helper.go
controllers/restore_controller.go
controllers/restore_post.go
controllers/restore_post_test.go
controllers/restore_test.go

https://issues.redhat.com/browse/ACM-5953
New output for restore (veleroGenericResourcesRestoreName); this will be used to find the backup name for the generic resources. Before this change, the generic resources backup name was computed from the resources backup and this could result in cleaning up generic resources  if the resources backup was not from the same schedule with the generic backup ( in that case, newly restored generic resources were identified as restored in another session and were cleaned by the post restore operation )
```
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
name: restore-acm-passive-sync
namespace: open-cluster-management-backup
spec:
cleanupBeforeRestore: CleanupRestored
restoreSyncInterval: 5m
syncRestoreWithNewBackups: true …
```

use generic backup name on cleanup

---

controllers/backup.go

https://issues.redhat.com/browse/ACM-4225
Move MultiClusterObservability to the active resource set since this resource once restored on the restore hub creates all obs resources using the backed secrets and configmaps; as a result it creates PV and PVClaims
We don't want to have these resources created until the very end, when the passive cluster becomes active

backup multiclusterobservability under active data backup

---

controllers/pre_backup.go
controllers/schedule_controller_test.go

Do not set spec.installNamespace on managed-serviceaccount ManagedClusterAddOn when creating it.
For: https://issues.redhat.com/browse/ACM-6967

remove MSA installNS on ManagedClusterAddOn

---

Dockerfile
go.mod

midstream repo is already building the downstream with golang 1.20
Downstream builds for release-2.6-2.9 are also using golang 1.20 - so will also update release-2.6, release-2.7, release-2.8 to golang 1.20

Update upstream to golang 1.20

---

controllers/pre_backup.go
controllers/pre_backup_test.go
controllers/schedule_controller_test.go

https://issues.redhat.com/browse/ACM-7569
Issue: 
When the MSA account uses a custom installNS, the ManifestWork pushing on the managed cluster the RoleBinding used to bind the MSA account to the klusterlet-bootstrap-kubeconfig role is incorrectly pointing to the `open-cluster-management-agent-addon` as the ServiceAccount ns, instead of the custom ns defined by the installNS property
As a result, when the restore tries to use the MSA token to reimport the cluster, the token doesn't have authority to perform the action
The fix:
For existing MSA accounts using a custom installNS, the code creates an extra ManifestWork named `addon-managed-serviceaccount-import-custom` 
On this resource it creates the rolebiding to the ServiceAccount using the custome ns
We don't update the existing …

use installNS when creating ManifestWork role binding

---

controllers/pre_backup.go
controllers/schedule_controller_test.go

https://issues.redhat.com/browse/ACM-8301
Issue:
Getting a webhook error when trying to update the ClusterDeployment and add the hive label used to bypass the claimed cluster deployment webhook validation which throws an error when the resource is recreated in a restore scenario
hive.openshift.io/disable-creation-webhook-for-dr: true
This work has been covered by this hive story
https://issues.redhat.com/browse/HIVE-1791
with this PR https://github.com/openshift/hive/pull/1729
This is the error we get now , trying to run a client.Update on the resource :
"admission webhook \"clusterdeploymentvalidators.admission.hive.openshift.io\" denied the request: ClusterDeployment.hive.openshift.io \"azr-pool-tn-cdfr7\" is invalid: spec.clusterMetadata: Invalid value: …

patch clusterDeployment with the disable-creation-webhook-for-dr label

---

controllers/create_helper.go
controllers/pre_backup.go
controllers/pre_backup_test.go

https://issues.redhat.com/browse/ACM-8348
https://issues.redhat.com/browse/ACM-8263
Issue:
1. in 2.8.2 For MSA accounts created in a ns different than the default addon, we create a custom ManifestWork to create a RoleBinding for the ServiceAccount in that ns
The issue is that the RoleBinding has the same name as the one created by the initial ManifestWork and since this is a global resource, both ManifestWork owns it. Each ManifestWork keep updating the RoleBinding 
```
oc get clusterrolebinding managedserviceaccount-import -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
creationTimestamp: "2023-10-25T15:42:54Z"
name: managedserviceaccount-import
ownerReferences:
apiVersion: work.open-cluster-management.io/v1
kind: AppliedManifestWork
name: …
```

create role binding for custom and default ns

---

controllers/pre_backup.go
controllers/pre_backup_test.go

related to PR https://github.com/stolostron/cluster-backup-operator/pull/443
adding a deletion of the custom manifestwork for the pair MSA , managedserviceaccount-import-pair 
This pair MSA is created at half time the lifespan of the initial MSA to increase the likelihood of a valid MSA token being available with any backup
oc get ServiceAccount -A | grep auto-import-account
open-cluster-management-addon-observability        auto-import-account                                1         11d
open-cluster-management-addon-observability        auto-import-account-pair                           1         6d2h

delete mwork for pair MSA

---

controllers/restore_post.go
controllers/restore_post_test.go

https://issues.redhat.com/browse/ACM-8406
Remove this secret as part of the post restore operation
`oc get secret -n open-cluster-management-addon-observability        observability-controller-open-cluster-management.io-observability-signer-client-cert`

remove obs secret on post restore

---

controllers/restore.go
controllers/restore_test.go

https://issues.redhat.com/browse/ACM-8904
https://issues.redhat.com/browse/ACM-8870
Exclude CRDs when restoring a backup using the `Restore.Spec.ExcludedResources` option

exclude CRDs from restore

---

controllers/restore.go
controllers/restore_controller.go
controllers/restore_post.go
controllers/restore_post_test.go

https://issues.redhat.com/browse/ACM-9475
When the restore passive operation is being used, when the activation data is restored by updating the veleroManagedClustersBackupName: latest on this resource, the activation resources might not be restored.
This is because the activation restore is trying to use the same velero restore as the sync restore, unless a new backup has been created when the activation is started.
https://github.com/stolostron/cluster-backup-operator/blob/main/config/samples/cluster_v1beta1_restore_passive_sync.yaml
Version-Release number of selected component (if applicable):
How reproducible:
Always with the steps below
1. Backup hub resources and create at least one resource R with this label : cluster.open-cluster-management.io/backup: …

activation resources may not be restored if sync restore

---

controllers/restore_controller.go
controllers/restore_controller_test.go

https://issues.redhat.com/browse/ACM-9503
When PVCs are backed up and restored using the volsync policy https://github.com/open-cluster-management-io/policy-collection/blob/main/community/CM-Configuration-Management/acm-volsync-hub-backup/README.md
we need to have a hook on the hub restore to allow the PVCs to be created by the volsync ReplicationDestination resource before the apps using that PVC is created. If this is not happening, the app uses the PVC before the PVC snapshot has been created and because of this it will corrupt the data
 
These are the details behind this approach:
1. all app resources which need to connect to the PVC should have the 
cluster.open-cluster-management.io/backup: cluster-activation label set so they are restored at the very end, when the managed clusters …

add wait for restore when pvc need to be created first

---

README.md
controllers/backup.go
controllers/backup_test.go
controllers/restore_post_test.go
controllers/schedule_controller_test.go
controllers/schedule_test.go
controllers/suite_test.go

https://issues.redhat.com/browse/ACM-9732
Changes as requested by the server foundation team
Exclude resources with the following API group suffix:
proxy.open-cluster-management.io
action.open-cluster-management.io
view.open-cluster-management.io
clusterview.open-cluster-management.io
Exclude the particular resources below:
placementdecisions.cluster.open-cluster-management.io
The following API group suffix or resources no longer exist in ACM 2.10, it's safe to remove them from both the code and the doc.
admission.cluster.open-cluster-management.io
admission.work.open-cluster-management.io
observabilityaddon
applicationmanager
certpolicycontroller
iampolicycontroller
policycontroller
searchcollector
workmanager

update backup resources based on server foundation request

---

controllers/create_helper.go
controllers/restore_controller.go
controllers/restore_test.go

https://issues.redhat.com/browse/ACM-9717
If a configMap with 
cluster.open-cluster-management.io/backup-pvc label is found during a restore operation, the backup operator must wait for the PVC to be created ( by the pvc policy , which also restores the snapshot using a volsync DestinationReplication) , before creating activation resources. This allow the PVC to be restored before the app using the pvc uses the volume.
The issue reported here : The operator waits for the PVC but if, during the wait, another credentials backup is created by the primary hub , the new credential is picked up and because the wait stops.
The wait should not resume if only credential backups have been restored.
Version-Release number of selected component (if applicable):
How reproducible:
Always
Steps to …

wait for pvc when only creds files were restored

---

controllers/backup.go

https://issues.redhat.com/browse/ACM-9732
server foundation team wants to keep the placementdecisions.cluster.open-cluster-management.io in the backup until a decision is made whether this is used

add back placementdecisions.cluster.open-cluster-management.io

---

controllers/pre_backup.go

related to https://issues.redhat.com/browse/ACM-9780
Any backed up ManifestWork should be restored at activation time, after managed cluster CRs

restore msa ManifestWork at cluster activation

---

controllers/pre_backup.go
controllers/pre_backup_test.go
controllers/restore_post_test.go
controllers/schedule_controller_test.go
controllers/suite_test.go
controllers/utils_test.go

https://issues.redhat.com/browse/ACM-10093
Issue: When restoring managed clusters data and auto-import-account MSA are used to connect to the clusters, the list of MSA used by the restore operation should only include tokens created by an MSA with the auto-import-account name
If not, other MSA secrets can be picked up to be used by the auto-import-secret and those tokens don't have authority to run the import operation
Fix:
When looking for MSA tokens filter out and get only the ones with a name prefix `auto-import-account`

filter out MSA tokens not used by auto-import

---

Dockerfile
go.mod
go.sum

(cherry picked from commit c5e78332d131b8f2b2d4343cc61e7fd432d4bee9)
cherry-picking PR: https://github.com/stolostron/cluster-backup-operator/pull/504 into release-2.8
For: https://issues.redhat.com/browse/ACM-10523

Update to use golang v1.21 (#504)

---

Dockerfile
Dockerfile.rhtap

Update upstream dockerfile to use ubi9 and also checkin Dockerfile.rhtap for konflux.
Committing to main and will ffwd to release-2.11

Ubi9 and konflux dockerfile

---

controllers/utils.go
controllers/utils_test.go
main.go

If Velero CRDs are missing, starting controllers will crash as they have a watch on velero Schedule and Restore resources.  Adding a check that only happens prior to controller startup so we can wait for the CRDs to appear.
In a loop, checking every 30s at startup (before starting manager & controllers):
- Check for Velero Schedule and Restore CRDs at startup
- If either are not present, do not start controllers

dependent crd checks at startup

---

controllers/restore.go
controllers/restore_post.go

https://issues.redhat.com/browse/ACM-11860
Create a dummy backup when a restore of managed clusters are being executed on the passive hub. 
This backup has label annotations for
- clusterID where the restore was completed
- clusterID where the backup was created
- backup name used to run the restore operation
- the backup TTL is set to use the default velero TTL 
This backup can be seen by all hubs connected to the same storage location so the information that a restore of managed clusters has been executed is available to all hubs
Sample 
```
apiVersion: velero.io/v1
kind: Backup
metadata:
name: acm-restore-clusters-20240523120542
uid: 98ae0b26-d0ab-4f42-8e74-f9c4e429e1a3
creationTimestamp: '2024-05-23T16:06:22Z'
namespace: open-cluster-management-backup
labels: …
```

generate a dummy backup when managed clusters are restored on a hub ( https://issues.redhat.com/browse/ACM-11860 )

---

controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_test.go

https://issues.redhat.com/browse/ACM-11876
related to https://github.com/stolostron/cluster-backup-operator/pull/537
Scenario:
- hubA is active, backup schedules running
- hubB is passive
- hubA goes down unexpectedly 
- admin restores managed clusters on hubB and hubB becomes active hub
- hubA starts up; the backup schedule is still enabled
- since hubB is now the active hub, hubA schedule should be disabled
Changes : 
If a BackupSchedule runs on this hub, on reconcile, check if any acm-restore-clusters backup resource was created after the BackupSchedule was created. 
If a acm-restore-clusters backup resource was found, created after the BackupSchedule was created, and created by a different hub, set the BackupSchedule to BackupCollision and remove velero schedules

show backup collision if restore activation run on another hub

---

controllers/restore.go
controllers/restore_post.go

Reverts stolostron/cluster-backup-operator#539
Decided this will not be backported to release-2.10

Revert "[release-2.10] generate a dummy backup when managed clusters are restored on a hub ( https://issues.redhat.com/browse/ACM-11860 )"

---

controllers/restore.go
controllers/restore_post.go

Reverts stolostron/cluster-backup-operator#540
Decided this will not go into release-2.9

Revert "[release-2.9] generate a dummy backup when managed clusters are restored on a hub ( https://issues.redhat.com/browse/ACM-11860 )"

---

controllers/backup.go
controllers/schedule_controller_test.go

https://issues.redhat.com/browse/ACM-12221
Allow resources which are part of the excluded CRDs to be backed up by generic backup, using the backup label.
Currently, the label is ignored if the CRD is part of the excluded list

allow excluded CRDs to be backed up using backup label (https://issues.redhat.com/browse/ACM-12221)

---

api/v1beta1/restore_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/cluster.open-cluster-management.io_restores.yaml
config/samples/cluster_v1beta1_restore_options.yaml
controllers/create_helper.go
controllers/restore.go
controllers/restore_controller_test.go

https://issues.redhat.com/browse/ACM-12973
Enable ACM restore support for the following velero restore options:
see https://velero.io/docs/main/api-types/restore/ CRD
- includedResources
- includedNamespaces
- OrLabelSelectors
- LabelSelector
- namespaceMapping
Added a sample that shows how to use some of the velero restore options when restoring the  ACM hub backup
We strongly recommend to review the cleanupBeforeRestore option and use cleanupBeforeRestore=None when restoring a subset of the data, as using cleanupBeforeRestore=CleanupRestored may clean up resources excluded by the restore filter criteria.

add support for velero restore filter options

---

controllers/restore.go
controllers/restore_controller_test.go

Related to https://github.com/stolostron/cluster-backup-operator/pull/650
https://issues.redhat.com/browse/ACM-12973
Changes:
When the orLabelSelector is used to filter out restored objects, the orLabelSelector will be ignored for the credentials and generic resources velero restore files, since they already use a labelSelector ( set by the backup operator ) to filter out resources with a cluster-activation label
LabelSelector and OrLabelSelectors are mutually exclusive so you can't use both
labelSelector set by ACM on the velero restore resource for credentials and generic resources:
```
labelSelector:
matchExpressions:
- key: cluster.open-cluster-management.io/backup
operator: In
values:
- cluster-activation
```

ignore orLabelSelector for credentials and generic resources restore

---

controllers/create_helper.go
controllers/restore.go
controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/utils.go
controllers/utils_test.go

https://issues.redhat.com/browse/ACM-12973
Related to
https://github.com/stolostron/cluster-backup-operator/pull/655 
https://github.com/stolostron/cluster-backup-operator/pull/650
Updates:
Allow using user defined OrLabelSelectors for restore files where the acm restore already defines a LabelSelector criteria. That would be for credentials and generic resources restore files, both using a LabelSelector to include or exclude cluster activation resources, based on the type or restore ( restore passive or active resources )
For the case when ACM defines a LabelSelector criteria for the velero restore, this is appended to the user defined selectors with the following rules
1. if the user defines a set of OrLabelSelectors rules, the req LabelSelectorRequirement will be injected
to each …

append activation label selector to user defined OrLabelSelector

---

controllers/restore.go
controllers/restore_test.go

https://issues.redhat.com/browse/ACM-13365
Set user label selectors on the velero restores by using a copy of the acm restore labels.
If using the acm restore labels directly, any update to this label would be reflected on all resources sharing the label selector - acm and velero restores.

make a copy of user labels

---

controllers/restore.go

https://issues.redhat.com/browse/ACM-13693
Issue 
The velero restore status could return a FinalizingPartiallyFailed status for a restore that would eventually get into a PartiallyFailed status
The code only checks for the PartiallyFailed status so when the velero restore was FinalizingPartiallyFailed, acm restore returned success
Fix
Updated the code to check if the velero status contains the FailedStatus string

check velero restore PartiallyFailed (https://issues.redhat.com/browse/ACM-13693)

---

controllers/backup.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go

https://issues.redhat.com/browse/ACM-14425
Fixed the ExcludedNamespace backup template to use the custom name of the local cluster
The local cluster is identified by the local-cluster annotation

get local cluster namespace using ManagedCluster annotation (https://issues.redhat.com/browse/ACM-14425)

---

.github/renovate.json

- uses main as base branch as well as older release-2.y branches
- does not include release-2.14 as main ffwds there

adding .github/renovate.json for konflux

---

.golangci.yml
Makefile
controllers/backup.go
controllers/backup_test.go
controllers/restore.go
controllers/restore_post.go
controllers/restore_post_test.go
controllers/restore_test.go
controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go
controllers/schedule_test.go
controllers/utils.go
controllers/utils_test.go

- Update to use golangci-lint v2 (v2.0.2 to be exact)
- migrate the .golangci.yml
- fix new linting issues picked up by the linter

Golangci lint update

---

controllers/create_helper.go
controllers/restore.go
controllers/restore_controller.go
controllers/restore_controller_test.go
controllers/restore_post.go
controllers/restore_post_test.go
controllers/restore_test.go
controllers/schedule.go
controllers/suite_test.go
controllers/utils.go
controllers/utils_test.go
hack/crds/operator.open-cluster-management.io_internalhubcomponents.yaml

https://issues.redhat.com/browse/ACM-10273
Issue : when the backup operator is disabled on MCH, all resources, including backup ns are deleted. The velero Restores have finalizers so if there are any acm Restore resources ( which own those resources ) , the ns is stuck in Terminating 
Fix: 
Try to watch the InternalHubComponent.operator.open-cluster-management.io resource and on delete action (named cluster-backup ), clean up all resources. This is defined by the stolostron multiclusterhub project https://github.com/stolostron/multiclusterhub-operator
Steps:
- add a watch for the InternalHubComponent.operator.open-cluster-management.io  ( unstructured resource  )
1. This watches on delete action. When this happens, it should delete all acm restores - tbd
- update the acm restore reconcile …

add restore finalizer

---

controllers/restore.go
controllers/restore_controller.go
controllers/restore_test.go

https://issues.redhat.com/browse/ACM-10273
related to https://github.com/stolostron/cluster-backup-operator/pull/978
Use controller client to update internalhubcomponent unstructured resource, instead of using the dynamic interface

replace dynamic interface updates with client calls

---

.tekton/cluster-backup-operator-acm-213-pull-request.yaml
.tekton/cluster-backup-operator-acm-213-push.yaml

- will be required for the enterprise contract, similar to hermetic builds

[release-2.13] konflux - enable build-source-image

---

.tekton/cluster-backup-operator-acm-211-pull-request.yaml
.tekton/cluster-backup-operator-acm-211-push.yaml
Dockerfile.rhtap

- will be required for the enterprise contract, similar to hermetic builds
(cherry picked from commit 1d85b9519398e8546a576af9a593cf149487081f)

konflux - enable build-source-image (#1003)

---

.github/renovate.json

- attempt to disable golang updates on older release branches (main/release-2.15 is the current)
- renovate will always do security updates, so security updates should still generate PRs, even to these branches

renovate disable golang updates for .Z branches

---

.github/renovate.json

- not building release-2.10 via konflux so remove renovate/mintmaker updates (they were there primarily to update the konflux tekton pipelines)

remove release-2.10 from renovate

---

controllers/pre_backup_test.go
controllers/schedule.go
controllers/schedule_controller.go
controllers/schedule_controller_test.go
controllers/schedule_test.go
controllers/utils.go
controllers/utils_test.go

Use quiet logging for tests that expect errors to avoid confusing PR output
PRs sometimes report a test error due to this expected test error
Fixed a fix race condition on schedule tests by testing missing schedule detection rather than testing the schedule recreation

[AI-assisted] Use quiet logging for tests that expect errors

---

.github/renovate.json

Disabling go.mod updates (for non-security) on older release branches has not been working.
Some updates to the renovate.json as suggested in a support ticket in `konflux-users` - see thread:
https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1755524348522629

fix renovate cfg for gomod updates

---

Dockerfile.rhtap

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini

chore(KONFLUX-6210): fix and set name and cpe label for cluster-backup-operator-acm-214

---

Dockerfile.rhtap

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Claude <noreply@anthropic.com>
Created-by: Claude AI

[release-2.13] chore(KONFLUX-6210): fix and set name and cpe label for cluster-backup-operator-acm-213
